### ISSUE TITLE
How to replace function that has more than one parameters

### ISSUE THREAD

**Issue by abc469** [coolxv/cpp-stub#2]
How to replace function that has more than one parameters

**Comment by coolxv** [comment]
//for linux，__cdecl
#include<iostream>
#include "stub.h"
using namespace std;
class A{
    int i;
public:
    int foo(int a,int b, int c){
        cout<< a << b << c <<endl;
        return 0;
    }
};

int foo_stub(void* obj, int a,int b, int c)
{   
    A* o= (A*)obj;
    cout<< a << b << c <<endl;
    return 0;
}


int main()
{
    Stub stub;
    stub.set(ADDR(A,foo), foo_stub);
    A a;
    a.foo(1, 2, 3);
    return 0;
}
