### ISSUE TITLE
ARM32 run Segment fault.

### ISSUE THREAD

**Issue by RelaxOne** [coolxv/cpp-stub#27]
compile command: `arm-linux-gnueabi-g++ test_object_member_function_linux.cpp -std=c++11 -I ../src -o test_object_member_funciton_linux`
then move to arm32 run it .
```
[root@DMD3A ~/bin]#./test_object_member_funciton_linux 
Segmentation fault
```

**Comment by coolxv** [comment]
try compile  test_object_member_function_win.cpp
```
arm-linux-gnueabi-g++ test_object_member_function_win.cpp -std=c++11 -I ../src -o test_object_member_funciton_win
```
Please provide more detailed information.

**Comment by RelaxOne** [comment]
Thanks for your answer, I fixed this yesterday because the parameter `-marm` is missing at compile time.
